### ISSUE TITLE
yolov4测试精度比较低

### ISSUE THREAD

**Issue by hufangjian** [ChenYingpeng/darknet2caffe#14]
你好，我这边从darknet转到caffe后，测试时发现精度比较低。有一些莫名其妙的框。

**Comment by Amore-HDU** [comment]
你好，我也在转caffe，精度差四五个点。
399498400@qq.com

**Comment by becauseofAI** [comment]
@hufangjian @Amore-HDU 
I had tested the converted result, which working rightly.

**Comment by kiddliao** [comment]
> 你好，我也在转caffe，精度差四五个点。
> [399498400@qq.com](mailto:399498400@qq.com)
你好 转换后怎么测试精度呢

**Comment by lxgyChen** [comment]
@hufangjian 你好!我这边转换不了yolov4,要做哪些修改呢？能指点一下吗？
转换报错：
`{1: 'layer1-conv', 2: 'layer2-conv', 3: 'layer3-conv', 4: 'layer4-route', 5: 'layer5-conv', 6: 'layer6-conv', 7: 'layer7-conv', 8: 'layer8-shortcut', 9: 'layer9-conv'}
Traceback (most recent call last):
  File "yolov3_darknet2caffe.py", line 536, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "yolov3_darknet2caffe.py", line 15, in darknet2caffe
    net_info = cfg2prototxt(cfgfile)
  File "yolov3_darknet2caffe.py", line 392, in cfg2prototxt
    bottom2 = topnames[prev_layer_id2]
KeyError: -6
`

**Comment by DaqiangSu2019** [comment]
> 你好，我这边从darknet转到caffe后，测试时发现精度比较低。有一些莫名其妙的框。

我转完之后也有莫名奇妙的框。。
